'use client'

import { useState } from 'react'
import ReactMarkdown from 'react-markdown'
import { Message as MessageType } from '@/types'

interface Props {
  message: MessageType
  currentModel: string
  onEdit?: (index: number, content: string) => void
  onRetry?: () => void
}

export default function Message({ message, currentModel, onEdit, onRetry }: Props) {
  const [editing, setEditing] = useState(false)
  const [editText, setEditText] = useState(message.content)
  const [hovered, setHovered] = useState(false)

  const isUser = message.role === 'user'
  const modelDiffers = message.role === 'assistant' && message.model_id && message.model_id !== currentModel

  const handleEditConfirm = () => {
    onEdit?.(message.message_index, editText)
    setEditing(false)
  }

  return (
    <div
      className={`group flex ${isUser ? 'justify-end' : 'justify-start'} mb-4`}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {/* Assistant avatar */}
      {!isUser && (
        <div className="w-7 h-7 rounded-full bg-black text-white flex items-center justify-center text-xs shrink-0 mt-1 mr-2">
          ✦
        </div>
      )}

      <div className={`max-w-[75%] ${isUser ? 'order-1' : 'order-2'}`}>
        {/* Images */}
        {message.image_urls && message.image_urls.length > 0 && (
          <div className="flex gap-2 mb-2 flex-wrap justify-end">
            {message.image_urls.map((url, i) => (
              <img key={i} src={url} alt="" className="max-w-[200px] rounded-xl border border-[#E5E5E5]" />
                ))}
          </div>
        )}

        {/* Bubble */}
        {editing ? (
          <div className="space-y-2">
            <textarea
              value={editText}
              onChange={e => setEditText(e.target.value)}
              className="w-full px-4 py-3 rounded-2xl border border-[#E5E5E5] text-sm outline-none resize-none"
              rows={3}
              autoFocus
            />
            <div className="flex gap-2 justify-end">
              <button
                onClick={() => setEditing(false)}
                className="text-sm text-[#6B6B6B] hover:text-[#0D0D0D]"
              >
                Cancel
              </button>
              <button
                onClick={handleEditConfirm}
                className="text-sm bg-black text-white px-3 py-1 rounded-lg"
              >
                Save & Resend
              </button>
            </div>
          </div>
        ) : (
          <div
            className={`px-4 py-3 rounded-2xl text-sm leading-relaxed ${
              isUser
                ? 'bg-gray-100 text-[#0D0D0D]'
                : 'bg-white text-[#0D0D0D] border border-gray-100 shadow-sm'
            }`}
          >
            {isUser ? (
              <p className="whitespace-pre-wrap">{message.content}</p>
            ) : (
              <div className="prose prose-sm max-w-none
  prose-p:my-1 prose-p:leading-relaxed
  prose-headings:font-semibold prose-headings:my-2
  prose-ul:my-1 prose-ol:my-1 prose-li:my-0.5
  prose-code:bg-gray-100 prose-code:px-1 prose-code:rounded prose-code:text-sm
  prose-pre:bg-gray-900 prose-pre:text-gray-100 prose-pre:rounded-xl prose-pre:p-4
  prose-strong:font-semibold prose-strong:text-[#0D0D0D]">
  <ReactMarkdown>
    {message.content}
  </ReactMarkdown>
</div>
            )}
          </div>
        )}

        {/* Model badge */}
        {modelDiffers && (
          <p className="text-xs text-[#6B6B6B] mt-1 px-1">
            Generated by {message.model_id}
          </p>
        )}

        {/* Actions */}
        {hovered && !editing && (
          <div className={`flex gap-2 mt-1 px-1 ${isUser ? 'justify-end' : 'justify-start'}`}>
            <button
              onClick={() => navigator.clipboard.writeText(message.content)}
              className="text-xs text-[#6B6B6B] hover:text-[#0D0D0D] transition-colors"
            >
              Copy
            </button>
            {isUser && onEdit && (
              <button
                onClick={() => setEditing(true)}
                className="text-xs text-[#6B6B6B] hover:text-[#0D0D0D] transition-colors"
              >
                Edit
              </button>
            )}
            {!isUser && onRetry && (
              <button
                onClick={onRetry}
                className="text-xs text-[#6B6B6B] hover:text-[#0D0D0D] transition-colors"
              >
                Retry
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  )
}